# -*- coding: utf-8 -*-
"""Orange_SML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fnwwesHt-drH8tVea9oJsg-fhrz1D3L7
"""

# ==========================================================
# HOUSEHOLD ANIMALS CLASSIFICATION (CATS vs DOGS)
# DEEP LEARNING | GOOGLE COLAB | SINGLE RUN CODE
# ==========================================================

# 1️⃣ IMPORT LIBRARIES
import tensorflow as tf
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
import numpy as np

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

print("TensorFlow Version:", tf.__version__)

# ----------------------------------------------------------
# 2️⃣ LOAD DATASET (AUTO DOWNLOAD)
# ----------------------------------------------------------
(train_ds, val_ds), ds_info = tfds.load(
    'cats_vs_dogs',
    split=['train[:80%]', 'train[80%:]'],
    as_supervised=True,
    with_info=True
)

print("Dataset loaded successfully")

# ----------------------------------------------------------
# 3️⃣ PARAMETERS
# ----------------------------------------------------------
IMG_SIZE = (224, 224)
BATCH_SIZE = 32

# ----------------------------------------------------------
# 4️⃣ PREPROCESSING FUNCTION
# ----------------------------------------------------------
def preprocess(image, label):
    image = tf.image.resize(image, IMG_SIZE)
    image = tf.cast(image, tf.float32) / 255.0
    return image, label

train_ds = train_ds.map(preprocess).shuffle(1000).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
val_ds = val_ds.map(preprocess).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

# ----------------------------------------------------------
# 5️⃣ BUILD MODEL (TRANSFER LEARNING)
# ----------------------------------------------------------
base_model = MobileNetV2(
    input_shape=(224, 224, 3),
    include_top=False,
    weights='imagenet'
)

base_model.trainable = False  # Freeze base model

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
output = Dense(1, activation='sigmoid')(x)

model = Model(inputs=base_model.input, outputs=output)

# ----------------------------------------------------------
# 6️⃣ COMPILE MODEL
# ----------------------------------------------------------
model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

# ----------------------------------------------------------
# 7️⃣ TRAIN MODEL (LESS EPOCHS FOR COLAB)
# ----------------------------------------------------------
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=5
)

# ----------------------------------------------------------
# 8️⃣ PLOT ACCURACY & LOSS
# ----------------------------------------------------------
plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title('Accuracy')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Loss')
plt.legend()

plt.show()

# ----------------------------------------------------------
# 9️⃣ TEST ON SAMPLE IMAGES
# ----------------------------------------------------------
class_names = ['Cat', 'Dog']

for images, labels in val_ds.take(1):
    preds = model.predict(images)
    plt.figure(figsize=(10,10))
    for i in range(9):
        plt.subplot(3,3,i+1)
        plt.imshow(images[i])
        pred_label = class_names[int(preds[i] > 0.5)]
        true_label = class_names[labels[i]]
        plt.title(f"Pred: {pred_label} | True: {true_label}")
        plt.axis('off')
    plt.show()

print("✅ Model training & testing completed successfully")